deploy/operator.yaml

Fixes #33 
I've pushed the current operator image to [`docker.io/pravega/pravega-operator`](https://hub.docker.com/r/pravega/pravega-operator/) and updated the image reference in the Yaml file.

[issue-33] Use Docker image from Pravega organization

---

pkg/pravega/pravega_segmentstore.go
pkg/pravega/sync.go
pkg/stub/handler.go

The Go errors in the `ReconcilePravegaCluster()` function were never handled correctly. That is, upon receiving an error by one of the called functions, the `err` variable would never be set.
This PR fixes this by explicitly setting the `err` variable every time a new call is made.
Signed-off-by: Olivier Bourgeois <olivier.bourgeois@emc.com>

Issue 74: Handle Go errors correctly

---

README.md
pkg/apis/pravega/v1alpha1/bookkeeper.go
pkg/apis/pravega/v1alpha1/pravega.go
pkg/pravega/bookie.go
pkg/pravega/pravega_controller.go
pkg/pravega/pravega_segmentstore.go

- Update PravegaCluster API spec to allow users to optionally set service account names for BookKeeper, Pravega Controller, and Pravega Segmentstore.
- Update Pod spec in StatefulSet and Deployment pod templates to include the service account names if they are set.
- Update README file with instructions on how to configure the non-default service accounts.
- Refactor README structure. Create a new "Configuration" section that includes existing configuration information.
- Fix #79 
Signed-off-by: Adrian Moreno <adrian@morenomartinez.com>

[WiP] Issue 79: Ability to configure non-default service accounts

---

.travis.yml
deploy/rbac.yaml
pkg/apis/pravega/v1alpha1/types.go
pkg/pravega/bookie.go
pkg/pravega/pravega_controller.go
pkg/pravega/pravega_segmentstore.go
pkg/utils/k8sutil/k8sutil.go
pkg/utils/k8sutil/pravega.go

This PR adds support for external connectivity (i.e. connectivity from outside the Kubernetes cluster). Below is a detailed description of the changes made and the reason why they were made.
As with the Bookies, Segmentstores are managed by a `StatefulSet`. Headless services provide DNS records for the Segmentstore set that can be used for intra-cluster communication, i.e., segmentstore pods can be access using the `<statefulset_name>-<ordinal>.<headless_service_name>` hostname (e.g. `pravega-segmentstore-1.pravega-segmentstore-headless` would resolve to the IP of second pod in the set).
Pravega clients need to be able to directly reach every Segmentstore instance. We found multiple ways to achieve this:
- Using `NodePort` services. `NodePort` services allocate a free port (within the …

Issue 61: Support external connectivity

---

pkg/pravega/sync.go

This PR adds the ability to scale the number of Controller replicas. It has been implemented in the `pkg/pravega/sync.go` file, in the same way as other components are scaled (Segmentstore, Bookkeeper), i.e., the code obtains the desired number of replicas from the updated manifest and makes sure the Controller `Deployment` object is in sync.
- Fix #82 
Checkout the repository (`master` branch is fine, no need to checkout this branch).
Edit the operator image used in the `deploy/operator.yaml` file to use the `adrianmo/pravega-operator:issue-82-1` image, which contains the changes in this PR.
Follow the instructions in the README file to install the operator, deploy the operator, and create a Pravega cluster.
By default, there will only be one Controller replica.
```
$ kubectl get all -l …
```

Issue 82: Ability to scale Pravega Controller

---

pkg/controller/pravega/bookie.go

- Change Bookie ID from using the pod's hostname to the IP address. 
Related to #116 
This is a temporary workaround to fix BookKeeper failover scenarios until Pravega's BookKeeper version is updated to 4.7 (WiP: https://github.com/pravega/pravega/pull/3192).
BookieFailoverTest should pass. 
---

Issue 116: Use IP address as Bookie ID

---

cmd/manager/main.go
pkg/apis/pravega/v1alpha1/bookkeeper.go
pkg/apis/pravega/v1alpha1/pravega.go
pkg/controller/config/config.go

- Add a test mode flag to disable replica restrictions. Otherwise, the operator will run as usual.
Related to #116 
BookieFailoverTest and MultiControllerTest should pass when the operator is started with the `-test` flag.
---

[Issue 116] Create a test mode flag to disable replica restrictions

---

README.md

Signed-off-by: Aparna <Aparna.Rr@emc.com>
For the issue `Tracking Issue: "Unable to mount volumes" error for segmentstore pods on PKS cluster due to `nfs-common` package not available in Kube nodes #`
Mentioned content was included in the trouble shooting section of README.md

Issue 106: Updating README.md

---

README.md

Add role and cluster role definitions when configuring Pravega cluster with external access enabled.

Update README: Add service account role definitions

---

README.md

Updated the readme.md
1. Changed the tag from 0.3.2 to 0.4.0 in the YAML template (pravega.yaml) in the section `Deploy a sample pravega cluster`.
2. Added the badges for license, godoc, travis-ci, go-report to the README.md.

Document update: README.md

---

example/cr-detailed.yaml
pkg/apis/pravega/v1alpha1/bookkeeper.go
pkg/apis/pravega/v1alpha1/pravega.go
pkg/apis/pravega/v1alpha1/zz_generated.deepcopy.go
pkg/controller/pravega/bookie.go
pkg/controller/pravega/pravega_controller.go
pkg/controller/pravega/pravega_segmentstore.go
pkg/controller/pravegacluster/pravegacluster_controller_test.go
pkg/test/e2e/e2eutil/pravegacluster_util.go

This PR will bring the following changes:
- Set adequate default resource requests and limits for Pravega components
- Expose those resource setting to allow custom configurations
- Replace static `Xmx` JVM option with the dynamic, Docker-aware flags `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap` which will set the heap memory size to the given Pod memory limit. (Ref: https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits)
At this moment, the PR is being used for testing with the goal of finding the suitable values for resource requests and limits.
Fix #130 
When defining the Pravega cluster specification in the YAML file, include the following options to set custom resource requests and limits for each Pravega component.
``` …
```

Issue 130: Ability to specify container resources

---

.travis.yml
pkg/controller/pravega/bookie.go
pkg/controller/pravega/pravega_controller.go
pkg/controller/pravega/pravega_segmentstore.go

- Set BookKeeper Java options using the `BOOKIE_MEM_OPTS`, `BOOKIE_GC_OPTS`, and `BOOKIE_GC_LOGGING_OPTS` environment variables instead of `BK_BOOKIE_EXTRA_OPTS`.
- Make Segmentstore, Controller, and BookKeeper processes exit and crash on out of memory errors.
- Fix CI triggers.
Fix #144
Related to #141 
After deploying a Pravega cluster, `kubectl exec` into the containers, list the processes with `ps aux`, and check that Java options are properly passed to the Java process. 
---

Fix Pravega and BookKeeper Java options

---

Makefile
README.md

- Add badge with latest release. It automatically updates the version when a release is published.
- Do not update `latest` Docker tag when release candidates are published.
---
Signed-off-by: wenqi <Wenqi.Mou@emc.com>

Release adjustments

---

Makefile

Fix Makefile. Note that the result of make -v in Travis is GNU Make 3.81 and we normally have 4.0+ version locally. 

Fix Makefile in make version 3.81

---

README.md
doc/manual-installation.md

- Add section to manually install/uninstall operator and Pravega to readme file.
- Add steps to manually uninstall operator and Pravega in `doc/manual-installation.md`.
Fix #191
Fix #182
---

Issue 191: Steps to manually uninstall operator and Pravega

---

pkg/webhook/webhook.go
pkg/webhook/webhook_test.go

Enable webhook to reject requests when cluster is upgrading
Fix #187
Unit test should pass

Issue 187: Webhook rejects requests when cluster is upgrading

---

charts/pravega-operator/Chart.yaml
charts/pravega-operator/values.yaml

Update default image tag in operator chart to 0.4.0
Fix #200
`helm install charts/pravega-operator --name foo` should install an operator with version 0.4.0
---

Update default image tag in operator chart

---

deploy/crd.yaml

In operator 0.3.2, the `Version` field is not printed while executing `kubectl get PravegaCluster`.
The result it currently gives is :-
```
NAME      DESIRED MEMBERS   READY MEMBERS   AGE
pravega   7                 2               15s
```
This fix includes the `Version` field to the result
Fixes #214
The code adds the `Version` field as an Additional Printer Column to the PravegaCluster CustomResourceDefinition in Operator 0.3.2
`kubectl get PravegaCluster` should give a result similar to this :-
```
NAME      VERSION              DESIRED MEMBERS   READY MEMBERS   AGE
pravega   0.5.0-2269.6f8a820   7                 1               12s
```

Issue 214: Adding version field to the output of `kubectl get PravegaCluster`

---

charts/pravega-operator/templates/crd.yaml
deploy/crd.yaml

When upgrading a Pravega Cluster in operator 0.4.0,  the `DESIRED VERSION` field is obtained as an empty field during entire upgrade process.
```
$ kubectl get pravegacluster
NAME           VERSION              DESIRED VERSION   DESIRED MEMBERS   READY MEMBERS   AGE
bar-pravega    0.5.0-2222.8ba5431                     5                 5               4m
```
Fixes #184 
The code populates the `DESIRED VERSION` field with the appropriate value
To reproduce the issue tried upgrading a sample Pravega Cluster from version `0.5.0-2222.8ba5431` to version `0.5.0-2236.5228e2d` and then running `kubectl get PravegaCluster`. The `DESIRED VERSION` field obtained was blank as mentioned in the issue.
Created a new operator image with the fix and …

Issue 184: `DESIRED VERSION` field from `kubectl get PravegaCluster` is blank during upgrade

---

Makefile
README.md
doc/troubleshooting.md
pkg/webhook/add_webhook.go

Add additional README for manual deployment and upgrade.
Fix #205 #217

Issue 205,217: Add additional README guide for manual deployment and upgrade

---

doc/troubleshooting.md

If we enable external access while deploying Pravega Cluster using kubectl client version `v1.10.x` or lower, the external ip details printed in the output of `kubectl get svc` are truncated. This is however solved in kubectl client versions `v1.11.x` and greater. The change simply adds documentation regarding the same in the `Troubleshooting` section of pravega operator.
Fixes #179

Issue 179: External-IP details truncated in older Kubectl Client Versions

---

pkg/apis/pravega/v1alpha1/pravegacluster_types.go
pkg/controller/pravega/pravega_segmentstore.go

Added external-dns annotation to segment store external service that can be used by external-dns provider  to assign a DNS name to the service.
Fixes #211
Added `domainName` to Pravega Cluster Spec, that can be set via manifest to arrive at the FQDN for a single segment store node.
FQDN for segment store pod = SegmentStore_Pod_Name.domainName. ( ends with a . )
Added annotation `external-dns.alpha.kubernetes.io/hostname` to external service for each segment store container.
If external access=true, but domain name is not set in manifest, it would default to "pravega.io"
1. In Pravega spec set externalaccess=true, and domainName=`example.com.
2 `kubectl svc pravega-pravega-segmentstore-0 -o yaml` should show : …

Issue 211: Adding annotation to segment store service for external dns

---

pkg/controller/pravega/bookie.go
pkg/controller/pravega/constants.go
pkg/controller/pravega/pravega_controller.go
pkg/controller/pravega/pravega_segmentstore.go
pkg/controller/pravegacluster/pravegacluster_controller_test.go

This PR preserves the heap dump files during pod restart when OOM happens.
Fix #242 
The heap dump will output to our specified directory, which is a mounted `emptyDIr`. Data in `emptyDIr` can survive the pod restart on the same node.
Trigger an OOM, see if heap dump is in the specified directory after pod restarts.

Issue 242: Preserve heap dump file

---

charts/pravega/templates/clusterrolebinding.yaml
charts/pravega/templates/pravega.yaml
charts/pravega/templates/role.yaml

The Segment Store fails to start with Pravega external connectivity is enabled using helm method of installation `$helm install charts/pravega --name bar --set zookeeperUri=pravega-zk-client:2181, externalAccess.enabled=true`, as the service account that is configured in the segment store pod lacks the appropriate permissions.
```
NAMESPACE     NAME                                                 READY   STATUS      RESTARTS   AGE
default       bar-pravega-bookie-0                                 1/1     Running     0          79s
default       bar-pravega-bookie-1                                 1/1     Running     0          79s
default       bar-pravega-bookie-2                                 1/1     Running     0          78s
default …
```

Issue 204: Segment Store start failure when external access is enabled

---

pkg/controller/pravegacluster/upgrade.go

The upgrade process waits indefinitely for the failed pod to recover and does not update the `Error` and `Upgrading` status appropriately.
**kubectl describe PravegaCluster output**
```
Status:
Conditions:
Last Transition Time:  2019-05-15T07:57:10Z
Last Update Time:      2019-05-15T07:57:10Z
Status:                True
Type:                  Upgrading
Last Transition Time:  2019-05-15T07:58:28Z
Last Update Time:      2019-05-15T07:58:28Z
Status:                False
Type:                  PodsReady
Status:                False
Type:                  Error
Current Replicas:        5
Current Version:         0.5.0-2222.8ba5431
Members:
Ready:
bar-pravega-bookie-1
bar-pravega-bookie-2
bar-pravega-pravega-controller-7d6cbd8554-b9pdv …
```

Issue 186: Detecting error/failure during upgrade

---

doc/auth.md
doc/configuration.md
pkg/apis/pravega/v1alpha1/pravegacluster_types.go
pkg/controller/pravega/constants.go
pkg/controller/pravega/pravega_controller.go
pkg/controller/pravega/pravega_segmentstore.go

Currently default credentials are used for  authentication and there is no way to specify "user defined" user/password for authentication. This change allows users to create a secret containing username,password,acl and use the same for authentication, by specifying secret location on pod using system property '-Dcontroller.auth.userPasswordFile' 
Fixes #239
A new field 'Authentication' with 2 enclosing values - enabled and ControllerAuthSecret have been added to ClusterSpec.
When Enabled is set to "true", user can specify the secret name that contains the authentication credentials. Note that user needs to create this secret ahead of specifying it in the manifest using a command like ` kubectl create secret generic controller-auth …

Issue:239 Accept auth secret

---

pkg/controller/pravega/pravega_controller.go

During an upgrade, the Controller which is deployed as a Kubernetes Deployment creates a new ReplicaSet and moves pods from the old ReplicaSet to the new one at a controlled rate. It however retains the older ReplicaSet even after the upgrade has been successfully completed, because the old ReplicaSet can be used to perform a rollback using `kubectl undo deployment/<deployment-name>`.
However we want to clean up the old ReplicaSets after a successful upgrade since we do not intent to perform an `undo` in order to rollback the Deployment.
Fixes #258
The code sets the `revisionHistoryLimit` field in the `spec` of the Controller Deployment which is used to specify how many old ReplicaSets for this Deployment we want to retain. The rest will be …

Issue 258: Cleaning up old resources post upgrade

---

doc/upgrade-cluster.md
pkg/apis/pravega/v1alpha1/status.go
pkg/controller/pravega/pravega_controller.go
pkg/controller/pravega/pravega_segmentstore.go
pkg/controller/pravegacluster/upgrade.go
pkg/controller/pravegacluster/upgrade_test.go
pkg/util/k8sutil.go
pkg/webhook/webhook_test.go

This PR will set Pravega upgrade condition to false if there are errors happen during the upgrade. The way to detect error is to see if there is any progress has been made during a timeout. 
Fix #186 
The code will put the updated pod number into the `upgrading condition` message. When checking the upgrade status, it will check if the updated pod number has changed, if it has changed, then update the changed number, which will also add a timestamp to the `upgrading condition`. If nothing changed, it will compare the current time with the timestamp in the condition, if the difference exceeds 10 minutes, it will return an error indicating that there is no progress for the last 10 minutes and the upgrade can be considered as failed.
TBD

Issue 183: Set upgrade error status

---

charts/pravega/templates/tests/clusterrole.yaml
charts/pravega/templates/tests/clusterrolebinding.yaml
charts/pravega/templates/tests/service_account.yaml
charts/pravega/templates/tests/test.yaml

Implementing helm test on the Pravega Cluster so that post an upgrade we can determine whether the upgrade was successful or not by simply running `helm test <release-name>`.
Fixes #262 
The helm test simply checks whether `PodsReady` status field of the Pravega Cluster is set to true or not which can be used to determine whether the Pravega Cluster is ready or not.
Run `helm test <release-name>`
If the PravegaCluster upgrade was successful and all pods are in Ready state then the test should pass, else it should fail.

Issue 262: Adding Helm Test for Pravega Cluster

---

doc/external-access.md
pkg/apis/pravega/v1alpha1/pravega.go
pkg/apis/pravega/v1alpha1/pravegacluster_types.go
pkg/apis/pravega/v1alpha1/zz_generated.deepcopy.go
pkg/controller/pravega/pravega_controller.go
pkg/controller/pravega/pravega_segmentstore.go
pkg/controller/pravegacluster/pravegacluster_controller_test.go

Enables different service types to be provided for Controller and SegmentStore for external access, while maintaining backward compatibility with existing Cluster Spec.
Adds support for specifying custom annotations on controller and segment store external services.
Fixes #244, #245
Code uses external access service type from fields `ControllerExternalServiceType` for controller and `SegmentStoreExternalServiceType` for SegmentStore under `spec.pravega`, if these are specified.
If these are not specified in the manifest, service type specified under `spec.ExternalAccess.Type` is used for both controller and segment store services.
If both values are not provided and external access is enabled, defaultServiceType (LoadBalancer) is used. …

Issue:244,255 Support custom annotations and separate service types for external access for Controller and Segment Store

---

.travis.yml

Signed-off-by: anishakj <anisha.kj@emc.com>
Modified GKE cluster to EKS in travis builds.
end to end tests will run on EKS cluster instead of GKE
Replaced GKE with EKS clusters and removed all gcloud commands.
Travis build should pass

Issue 276: Modified cluster to EKS in travis build

---

pkg/webhook/webhook.go
pkg/webhook/webhook_test.go

Currently we are allowed to modify the `version` field of PravegaCluster through `kubectl edit PravegaCluster` when there is an active rollback is going on.
This should be restricted by the admission webhook.
Fixes #283
The code restricts the alteration of the `version` field of the PravegaCluster through `kubectl edit PravegaCluster` command during an active rollback.
When the cluster is in Rollback State, updation of the version field for the PravegaCluster will display the following error
```
$ kubectl edit PravegaCluster
error: pravegaclusters.pravega.pravega.io "pravega" could not be patched: Internal error occurred: admission webhook "pravegawebhook.pravega.io" denied the request: failed to process the request, cluster is in rollback …
```

Issue 283: Restricting modification of version field during active rollback

---

pkg/controller/pravega/pravega_segmentstore.go
pkg/controller/pravegacluster/pravegacluster_controller_test.go

SegmentStoreSvcAnnotations added to the manifest file are not visible in the kubectl describe output for the segmentStoreSvc if the domainName field is empty.
Fixes #289 
The code populates the SegmentStoreSvcAnnotations from the manifest file if external access has been enabled.
Add SegmentStoreSvcAnnotations to the manifest file 
```
pravega:
segmentStoreSvcAnnotations:
service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: "abc"
```
Deploy PravegaCluster with external access enabled. The describe output for the segmentStoreSvc should contain the added segmentStoreSvcAnnotations key-value pairs as part of `Annotations` field of the output.
```
$ kubectl describe svc bar-pravega-pravega-segmentstore-0
Name: …
```

Issue 289: Adding SegmentStoreSvcAnnotations

---

pkg/controller/pravegacluster/pravegacluster_controller.go
pkg/controller/pravegacluster/pravegacluster_controller_test.go
pkg/test/e2e/e2eutil/pravegacluster_util.go
pkg/util/pravegacluster.go

When we deploy PravegaCluster with external access enabled and scale down the segmentstore to a lower instance count, the service entries for the segmentstore were not getting deleted.
Fixes #289 
To reproduce the issue, deployed a sample Pravega Cluster with 3 segmentstore replicas and with external access enabled. Updated the number of segmentstore replicas in the spec to 1 and observed that while the extra segmentstore replicas were getting deleted, the extra segmentstore services were left behind.
```
$ kubectl get all
NAME                                                       READY   STATUS    RESTARTS   AGE
pod/pravega-bookie-0                                       1/1     Running   0          164m
pod/pravega-bookie-1 …
```

Issue 287: Deleting SegmentStore Services after Scaledown

---

charts/app/configmap.yaml
charts/app/pravega-cluster.yaml
charts/pravega/templates/pravega.yaml
pkg/apis/pravega/v1alpha1/status.go
pkg/controller/pravegacluster/upgrade.go
pkg/util/k8sutil.go

This change enables operator to emit K8s Events for failures that need human intervention.
Error Events are emitted for `Upgrade Failure` and `RollbackFailure`.
Fixes #273.
Events should get added to kubernetes event queue, when upgrade fails and rollback fails.
The following is the describe output of the event that is created.
```
Name:             UPGRADE_ERROR
Namespace:        default
Labels:           app=pravega-cluster
pravega_cluster=pravega
Annotations:      <none>
API Version:      v1
Event Time:       <nil>
First Timestamp:  2019-11-07T19:50:12Z
Involved Object:
API Version:       pravega.pravega.io/v1alpha1
Kind:              pravegacluster
Name:              pravega
Namespace:         default
Resource Version:  2333666
UID:               1be047dc-0197-11ea-84b4-005056b2ae40 …
```

Issue 273: Publish Events for Critical failures

---

README.md
pkg/controller/pravegacluster/pravegacluster_controller.go

Adds a log message to be printed once zookeeper metadata has been cleaned up. Also, updates the README stating that the Pravega Operator should not be deleted till this log has been printed to the operator logs indicating that the zookeeper metadata has been cleaned up.
Fixes #307

Issue 307: Operator uninstall documentation update

---

pkg/apis/pravega/v1alpha1/status.go
pkg/webhook/webhook.go
pkg/webhook/webhook_test.go

When checking for values updated in the `version` field it is important to consider the cluster state and then based on that decide if the updated value is correct or not.
Fixes #309 
Checks for cluster state and version validation logic changes based on cluster state.
```
if ( cluster in pods ready state)
{ version change leads to upgrade, check upgrade compatibility matrix  }
else if (cluster in upgrade failed state)
{ version change should lead to rollback if (request version != last stable cluster version) reject request }
}
```
Should be able to trigger rollback when version feild is updated to `0.6.1-2419.5ae9098`
when upgrade fails from version  `0.6.0-2408.7312399` to `0.6.1-2419.5ae9098`

issue:309 fix for webhook check failure for rollback

---

doc/tier2.md
example/cr-detailed.yaml
pkg/apis/pravega/v1alpha1/pravega.go
pkg/controller/pravega/pravega_segmentstore.go
pkg/controller/pravega/pravega_segmentstore_test.go

Signed-off-by: kevinhan88 <kevinhan88@gmail.com>
The ECS config item "root" is renamed to "prefix" per https://github.com/pravega/pravega/issues/4550
This is the corresponding change in operator.
Fixes #322 
Replaced "root" with "prefix" in the following files:
pravega_segmentstore_test.go
cr-detailed.yaml
pravega_segmentstore.go
pravega.go
tier2.md
The operator should function as usual with the new ECS config item "prefix".

Issue-322: renamed ECS config item root to prefix

---

doc/upgrade-cluster.md

While upgrading pravega from version 0.X to 0.Y (X<7, Y>=7), there are configuration changes that must be made to pravega manifest (because 0.7 onwards we no longer use Rocks DB) to make sure we have setup memory and other pravega parameters appropriately for segment store streaming cache to work as expected.
Fixes #329 
Documents the changes that need to be made to the manifest before triggering the upgrade from version 0.X to 0.Y (X<7, Y>=7).
After making the changes mentioned in the document, the user should be able to successfully upgrade Pravega from a version < 0.7 to a version >= 0.7

Issue 329: Updating upgrade documentation

---

doc/tier2.md
example/cr-detailed.yaml
pkg/apis/pravega/v1alpha1/pravega.go
pkg/controller/pravega/pravega_segmentstore.go
pkg/controller/pravega/pravega_segmentstore_test.go

Signed-off-by: kevinhan88 <kevinhan88@gmail.com>
Started using configUri for ECS client side configuration
Closes #325 
tier2.md, cr-detailed.yaml: rename "uri" to "configUri"; removed namespace as it should now show up as part of configUri
pravega.go, pravega_segmentstore.go, pravega_segmentstore_test.go: refactored ECSSpec struct - renamed "uri" to "configUri" and removed namespace
_(Detailed description of the code changes)_
The Pravega Operator syncs up the ECS configUri in the following way:
If "identity" and "secretKey" are present in the ECS configUri, then operator will pass the uri directly into Pravega, ignoring ecs-credentials if any;
If "identity" or "secretKey" is not present on ECS configUri, then operator will look into K8S secret. If ecs credentials are found inside k8s …

Issue-325: started using configUri for ECS tier-2

---

README.md
charts/pravega-operator/templates/operator.yaml
charts/pravega-operator/values.yaml
doc/manual-installation.md

Added a flag `testmode` in  `values.yaml` file, so that user can run operator in test mode if required.
Added documentation.
Fixes #324
Added a flag `testmode` in  `values.yaml` file, so that user can run operator in test mode if required.
Added documentation.
Able to deploy operator in `testmode` by changing `operator.yaml` file for manual installation and by changing `charts/values.yaml` for  installation via charts.

Issue 324: Added testmode flag in charts

---

doc/development.md

Fixed a typo in the instead of  **go get github.com:pravega/pravega-operator** it should be **go get github.com/pravega/pravega-operator**

Updated development.md

---

.travis.yml
charts/pravega-operator/templates/clusterrole.yaml
charts/pravega-operator/templates/operator.yaml
charts/pravega-operator/values.yaml
deploy/operator.yaml
deploy/role.yaml

Configured `WATCH_NAMESPACE`  field in Helm charts.
Fixes #311 
Added new configuration param in `values.yaml` file, so that WATCH_NAMESPACE can be configured. Added new cluster roles in pravega-operator so that it can install pravega-components in different name space ,other than the  one in which operator is running.
Tried installing operator and pravega-components in same and different namespaces and deployments were successful.

Issue 311: Helm chart should allow watch namespace to be passed in.

---

README.md
charts/pravega-operator/Chart.yaml
charts/pravega-operator/values.yaml
charts/pravega/Chart.yaml
charts/pravega/values.yaml
deploy/crds/pravega_v1alpha1_pravegacluster_cr.yaml
doc/rbac.md
doc/rollback-cluster.md
example/cr-detailed.yaml
pkg/apis/pravega/v1alpha1/pravegacluster_types.go

Updates the pravega operator version to `latest` inside the charts repo.
Fixes #359 
Updates the pravega operator version to `latest` inside the charts repo.
The latest operator version should get installed when we run the following command
```
$helm install charts/pravega-operator
```

Issue 359: Updating charts to use latest operator version

---

go.sum
pkg/controller/pravega/pravega_segmentstore.go
pkg/controller/pravegacluster/pravegacluster_controller_test.go
pkg/controller/pravegacluster/upgrade.go
pkg/util/pravegacluster.go

In pravega operator `0.5`, we are creating STS with different name that  in turn changes pod name. Due to that init script of pravega is failing as  it assumes pod name is same service name.  And segment containers are not coming up.POD_NAME is passed as env variable from operator to pravega init script
Fixes #354
From 0.7 pravega onwards, pod name and external service names were different with 0.5 operator.
Changed external service name to pod name, so that external service name and pod name will have the same name in every pravega version. Also while doing upgrade from 0.6 to 0.7, delete the external services and create services with same name of pravega-0.7 segment store pods.
Tested the below scenarios with external connectivity
1. Able to …

Issue 354: Segment store pods are not coming up with external access

---

pkg/apis/pravega/v1beta1/pravegacluster_types.go

The k8s events generated by Pravega Operator do not have unique names because of which KAHM is unable to consume multiple occurences of the same event, as it can only consume events which have unique names.
Fixes #375 
It uses `GenerateName` field instead of the `Name` field which suffixes the name with a unique random string.
The event added to kubernetes event queue, whenever  an upgrade or rollback of the pravega cluster fails is of the following format (if u notice the name of the generated event, the last five characters are random unique characters which are suffixed to the actual name, thereby producing unique event names)
```
Name:             UPGRADE_ERROR-4gklf
Namespace:        default
Labels:           app=pravega-cluster …
```

Issue 375: Generating unique names for events

---

charts/pravega/templates/pravega.yaml

Fixed typo in the pravega.yaml file
longtermStorage had a typo in it and needed to be changed 
It will ensure we have correct long term storage deployed
deploy pravega cluster using charts

Fixed typo in the pravega.yaml file

---

example/cr-detailed.yaml
go.sum
pkg/apis/pravega/v1beta1/pravega.go

updated cr-detailed.yaml file and made the cacheVolumeClaimTemplate optional
To provide a sample manifest file 
Now the **cacheVolumeClaimTemplate**  is made optional so there is no need to provide it in case pravega version is >=0.7
Deploy the manifest file  **example/cr-detailed.yaml**

updated cr.yaml

---

pkg/controller/pravega/pravega_segmentstore.go

With the newer controller run time library, setting owner reference to cachevolume template was failing with error `failed to set ownerref: cluster-scoped resource must not have a namespace-scoped owner, owner's namespace default`. Due to which while deleting cluster pvc's are not deleted. Made the changes to create volumeclaim template in cluster namespace, so that owner reference is set correctly.
Fixes #390
Created cache volumeclaims in the same namespace where pravega cluster is created
Verified that owner reference is set correctly and pvcs are getting deleted while deleting cluster

Issue 390: Segment store pvcs are not getting deleted  even after pravega cluster deletion

---

doc/tier2.md
pkg/apis/pravega/v1alpha1/pravegacluster_types.go
pkg/controller/pravega/constants.go
pkg/controller/pravega/pravega_segmentstore.go
pkg/controller/pravega/pravega_segmentstore_test.go

This PR is cherry-pick of changes in PR https://github.com/pravega/pravega-operator/pull/349
Fixes #348 
When ECS certificate is defined as "pravega/tls/static/ca-bundle" inside Pravega yaml file, the operator mounts it onto "/etc/secret-volume/ca-bundle" in Segmentstore container.
Then container adds the certificate into Java Truststore in order to establish secured connection with ECS.
_(Steps to verify that the changes are effective)_

Issue348: added ECS TLS secret into general pravega tls section

---

pkg/controller/pravega/pravega_controller.go
pkg/util/pravegacluster.go
pkg/util/pravegacluster_test.go

Pravega-operator marks pravega deployment as Ready before pravega is operational so a readiness check is needed to ensure pravega deployment doesn't mark pravega ready before it actually is.
This pr fixes #404 
This code introduce readiness check for the controller pod and will only mark controller ready when it's actually ready and is able to create scopes and streams.
1) To verify this I have deployed pravega and it marked controller in ready state only when the 
controller is able to create stream and scopes.
2) I have also verified by deploying pravega where the controller was not able to create scope and 
in that case, pravega deployment didn't mark the deployment ready.

Issue 404 : Added Readiness check for controller

---

cmd/manager/main.go

Added leader election as part of operator
Fixes #372
Added leader election back
Verified that no hangs are observed with more  number of operator replicas. 
Perform fail over and ensure other pod is becoming leader.
Upgrade the operator and ensure all pods are coming fine

Issue 372: Added leader election

---

README.md
charts/pravega/README.md
charts/pravega/values.yaml
deploy/crds/cr.yaml
example/cr-detailed.yaml
pkg/apis/pravega/v1alpha1/pravegacluster_types.go
pkg/apis/pravega/v1alpha1/pravegacluster_types_test.go
pkg/apis/pravega/v1beta1/pravegacluster_types.go
pkg/apis/pravega/v1beta1/pravegacluster_types_test.go
test/e2e/resources/bk-cluster.yaml
test/e2e/resources/bk-config-map.yaml
test/e2e/resources/zookeeper.yaml

Modifies the default name of the zookeeper client service from `zk-client:2181` to `zookeeper-client:2181` which is the default value created by zookeeper.

Changing default name of zookeeper service

---

charts/pravega/README.md
charts/pravega/values.yaml
charts/pravega/values/large.yaml
charts/pravega/values/medium.yaml
charts/pravega/values/minikube.yaml
charts/pravega/values/small.yaml

Provides 4 different kinds of manifests (i.e. small, medium, large and minikube) which provide the user more flexibility in deploying a cluster with the required number of component replicas, resources and required options without having to override those values individually.
Fixes #421 
To install a cluster with the resource requirements that would work on a minikube environment, use the following command
```
helm install pravega charts/pravega --values charts/pravega/values/minikube.yaml
```
It will successfully install a pravega cluster with the required replicas, resources and options.
Similarly user can give any of the following commands depending on his particular use-case
```
helm install pravega charts/pravega --values …
```

Issue 421: Adding manifests for various cluster installation flavours

---

charts/pravega-operator/README.md
charts/pravega-operator/templates/operator.yaml
charts/pravega-operator/templates/version_map.yaml
charts/pravega-operator/values.yaml

The pravega-operator should provide users a way to deploy a non-valid image version in non-production environments, since currently there doesn't seem to be any way to use the pravega-operator charts (without modifying them) to deploy pravega versions that are not already part of the version map.
Fixes #394 
When test-mode is enabled in the pravega-operator, the major version that is provided by the user within `testmode.version` is added to the supported-versions configmap that is created by the operator.
Provide the image version (major version number) that you wish to deploy which is not part of `version_map.yaml` by first enabling test-mode in the pravega-operator values.yaml file in the following way
```
testmode:
enabled: true …
```

Issue 394: Allowing non-valid image versions to be used in non-production environments

---

pkg/util/pravegacluster.go

ReadinessCheck in case of only auth enabled is added
fixes #425 
It checks if the controller pod is ready in case only auth is enabled.
Deploy pravega cluster with only Auth enabled and check for the controller pod to become ready

Issue 425: Readinesscheck for only auth added

---

charts/pravega-operator/templates/post-install-upgrade-hooks.yaml
charts/pravega-operator/values.yaml

* Adds a manifest which defines a post-install/upgrade hook to make sure the `pravegacluster` resource exists.
* If one is unlucky with the timings when install the `pravega-operator` chart, directly followed by the `pravega` chart, the api-resource `PravegaCluster` may not exist by the time the pravega chart tries to create a `PravegaCluster`.
* See above.
Run many install/uninstall cycles of the mentioned charts -- see that the pravega chart does not start before its resource dependency is registered.

Pravega Operator API Resource Hook.

---

pkg/controller/pravega/pravega_controller.go
pkg/util/pravegacluster.go
pkg/util/pravegacluster_test.go

The controller Readiness probe is failing in case of ingress
fixes #432 
The code here does a readiness check for controller in the following 4 cases 
1) Auth and TLS Enabled- in this case we check for the controller is properly enabled with authentication or not and we do a get on controller and with Dummy credentials(testtls:testtls) and the controller returns 401 error in this case if it's correctly configured
2) Auth Enabled and TLS Disabled- in this case, we check for the controller is properly enabled with authentication or not and we do a get on controller and with Dummy credentials(testtls:testtls) and the controller returns 401 error in this case if it's correctly configured
3) Auth Disabled and Tls Enabled- in this case we check if the controller is able to create scopes or not …

Issue 432: Controller Readiness probe is failing in case of ingress

---

.travis.yml

In travis, we were waiting for 5 min for cluster creation to complete. But in some cases cluster creation takes more time.Add a retry logic, and check whether the cluster state is active.
Add retry mechanism to check cluster is active.
Add retry mechanism to check cluster is active.
Make sure cluster creation is happening.

Modifying travis to add retry logic

---

doc/operator-upgrade.md
doc/upgrade-cluster.md
scripts/post-upgrade.sh
scripts/pre-upgrade.sh
tools/operatorUpgrade.sh

After upgrading the pravega operator from 0.4.5 to 0.5.1 via helm, the post-upgrade script which is used to upgrade the corresponding pravega release, does not reuse the values of its parameters from the existing setup. Instead, all these parameters are reset to their default values that have been specified in the new helm charts, which is undesirable.
Fixes #445 
- Accepts the bookkeeper replica count as an additional parameter in the post-upgrade script.
- Uses the `reuse-values` option while upgrading the pravega helm chart in order to preserve the properties that were set at the time of initial installation.
After the operator upgrade completes, run the post-upgrade script in the following way
```
$ ./post-upgrade.sh <name of pravega …
```

Issue 445: Reuse values for helm releases in post-upgrade script

---

pkg/controller/pravegacluster/upgrade.go
pkg/controller/pravegacluster/upgrade_test.go

Rollback fails in case of only 1 Segment Store Pod
Fixes #449 
This code changes the order of rollback in case of 1 ss i.e first the ss get's rollback then the controller which ensures readiness check doesn't fail and the rollback is successful.
Deploy pravega with 1 ss pod and try and upgrade and fail the upgrade process then rollback the cluster and first ss should get rollback then the controller.

Issue-449: Rollback fails in case of only 1 Segment Store Pod

---

.travis.yml
test/e2e/pravegacluster_test.go
test/e2e/upgrade_test.go

While executing e2e tests on CNCF cluster, it is not taking the correct branch where PR is raised
Fixes #457 
Following changes will ensure the travis build runs on the current branch and execute the e2e test on it
Travis build should pass.

Issue-457: Travis build is always taking the master branch for running e2e tests 

---

charts/pravega/README.md
doc/manual-installation.md
doc/pravega-options.md
doc/upgrade-cluster.md
pkg/controller/pravega/pravega_controller.go
pkg/controller/pravega/pravega_segmentstore.go

Removed the deprecated JVM option `UseCGroupMemoryLimitForHeap` and replaced with `UseContainerSupport`
Fixes #300
Replaced the deprecated JVM option and made documentation changes.
Install pravega 0.9.0 using 0.5.1 operator by setting IgnoreUnrecognizedVMOptions
Install pravega 0.9.0 using 0.5.2 operator

Issue300: JVM options incompatible with Java 11 environment

---

pkg/apis/pravega/v1beta1/pravegacluster_types.go
pkg/apis/pravega/v1beta1/pravegacluster_types_test.go
pkg/controller/pravega/pravega_controller.go
pkg/controller/pravega/pravega_segmentstore.go
pkg/controller/pravegacluster/pravegacluster_controller.go
pkg/test/e2e/e2eutil/pravegacluster_util.go
pkg/util/pravegacluster.go
pkg/util/pravegacluster_test.go
test/e2e/cmchanges_test.go
test/e2e/pravegacluster_test.go

This pr will enable the user to modify both controller and sgmentstore JVMOptions as well as options during runtime
Fixes #464 
The code looks for any change in the jvm option or option in either of controller or segmentstore and if there is a change i.e user has changed any of the jvmOptions or options or has added a new value, in that case, we update the configmap and restart each pod one by one.
I am doing validation as well and is done by the method **validateConfigMap()** which ensures user doesn't change any of the following values:-
1) controller.containerCount
2) controller.container.count
3) pravegaservice.containerCount
4) pravegaservice.container.count
5) bookkeeper.bkLedgerPath
6) bookkeeper.ledger.path
7) …

issue-464:Added support for JvmOption customization

---

charts/pravega-operator/templates/pravega.pravega.io_pravegaclusters_crd.yaml
charts/pravega/README.md
charts/pravega/templates/pravega.yaml
charts/pravega/values.yaml
deploy/crds/pravega.pravega.io_pravegaclusters_crd.yaml
pkg/apis/pravega/v1beta1/pravega.go
pkg/apis/pravega/v1beta1/pravegacluster_types.go
pkg/apis/pravega/v1beta1/zz_generated.deepcopy.go
pkg/apis/pravega/v1beta1/zz_generated_deepcopy_test.go
pkg/controller/pravega/pravega_controller.go
pkg/controller/pravega/pravega_controller_test.go
pkg/controller/pravega/pravega_segmentstore.go
pkg/controller/pravega/pravega_segmentstore_test.go
test/e2e/resources/crd.yaml
tools/manifest_files/crd.yaml

Pravega with ECS as LTS is failing to deploy in Openshift environment, as container needs to inject cert bundle into trust store, but the security context selected by openshift is preventing it.
To solve the above problem we have to set runAsUser = 0 for  pravega segmentstore sts.
Fixes #468 
These changes allow the segmentstore pod's to run as root user. For enabling this user has to give the following things in the manifest file while deploying it manually
```
pravega:
segmenStoreSecurityContext: 
runAsUser: 0  
```
If he is using charts he needs to uncomment the line in the values.yaml in the pravega charts:-
```
segmentStoreSecurityContext: 
runAsUser: 0
```
For controller he needs to set like this:-
```
controllerSecurityContext: …
```

Issue-468: Run pravega segmentstore sts with runAsUser = 0

---

.travis.yml
README.md
pkg/test/e2e/e2eutil/pravegacluster_util.go

Currently, all subsequent e2e-test fail once one of the e2e test fails and replaced **https://kubernetes-charts.storage.googleapis.com** with **https://charts.helm.sh/stable** for installing nfs server as it's no longer supported .
Fixes #472 
code deletes tier2 storage only when it's present
Travis build should run and all test should pass.

Fixing e2e test to allow other test to run post one test faliure

---

charts/pravega-operator/Chart.yaml
charts/pravega-operator/README.md
charts/pravega-operator/templates/webhook.yaml
charts/pravega-operator/values.yaml
charts/pravega/README.md
charts/pravega/templates/pravega.yaml
charts/pravega/values.yaml
test/e2e/resources/bookkeeper.yaml

Currently even when the longTermStorageType is set to `ecs` or `hdfs` within the values.yaml, the ecs or hdfs configuration is not taking effect and the longTermStorageType  of the deployed pravega cluster is getting set to filesystem in all cases.
Fixes #473  , #470 
Following use-cases have been tested :
- Deployed pravega cluster with storageType = ecs
- Deployed pravega cluster with storageType = hdfs
- Deployed pravega operator 0.4.5 with v1alpha1 pravega cluster. Upgraded the pravega operator to 0.5.2 followed by upgrading to v1beta1 pravega cluster.
- Deployed pravega operator by setting webhookCert.generate within values.yaml to true and confirmed that the correct certificate name is used.

Issue 473: Fixing charts to set the required LTS type

---

pkg/controller/pravegacluster/upgrade.go

With the upgrade of controller runtime, the updated `client.List` method does not return the list of pods in a sorted order, which was breaking the sequential one-pod-at-a-time upgrade logic that had been implemented in the operator for the segmentstore statefulset.
Fixes #477 
The list of pods returned by the `client.List` method is sorted by name before doing any further processing, to maintain consistency with the previous segmentstore upgrade logic.
Upgrade the pravega cluster from one version to another and ensure that not more than one segmentstore pod is upgraded at any given time.

Issue 477: Handling Segmentstore STS upgrade

---

doc/operator-upgrade.md

Added documentation changes in `operator-upgrade.md`
Fixes #485 
Document update
Document updated correctly

Issue 485: Documentation changes for operator upgrade

---

charts/pravega-operator/templates/pravega.pravega.io_pravegaclusters_crd.yaml
charts/pravega/README.md
charts/pravega/templates/pravega.yaml
charts/pravega/values.yaml
deploy/crds/pravega.pravega.io_pravegaclusters_crd.yaml
pkg/apis/pravega/v1beta1/pravega.go
pkg/apis/pravega/v1beta1/pravegacluster_types.go
pkg/apis/pravega/v1beta1/zz_generated.deepcopy.go
pkg/controller/pravega/pravega_controller.go
pkg/controller/pravega/pravega_segmentstore.go
test/e2e/resources/crd.yaml
tools/manifest_files/crd.yaml

Made the pod affinity configurable for controller and segment store pods.
Fixes #364 
Added affinity as configurable option in charts, and if not specified it will set the default anti affinity policy.
Verified that affinity configuration is working fine for controller and segment store pods.

Issue 364: Enable Pravega Pods to be run on Specific K8s Nodes

---

charts/pravega/templates/pravega.yaml
pkg/apis/pravega/v1beta1/pravegacluster_types.go
pkg/controller/pravegacluster/pravegacluster_controller_test.go

Pravega webhook fails upgrade even when just the name of the configuration keys is modified as per the new naming convention (ref. https://github.com/pravega/pravega/pull/4713)
Fixes #491 
Upgrade pravega from version 0.7.0 to 0.8.0 and along with it also modify the name of the pravega option name from `controller.containerCount` to `controller.container.count` without modifying its value. The upgrade should be allowed and you should not see the following error message
```
cannot patch "nautilus" with kind PravegaCluster: admission webhook "pravegawebhook.pravega.io" denied the request: controller.container.count should not be changed
```

Issue 491: Handling config key name changes

---

.github/workflows/CI.yml
charts/pravega-operator/templates/pravega.pravega.io_pravegaclusters_crd.yaml
charts/pravega/README.md
charts/pravega/templates/pravega.yaml
charts/pravega/values.yaml
deploy/crds/pravega.pravega.io_pravegaclusters_crd.yaml
pkg/apis/pravega/v1beta1/pravega.go
pkg/controller/pravega/pravega_controller.go
pkg/controller/pravega/pravega_segmentstore.go
pkg/controller/pravegacluster/pravegacluster_controller.go
pkg/controller/pravegacluster/pravegacluster_controller_test.go
test/e2e/resources/crd.yaml

This pr helps prevent segmentstore and controller pods from evicting if number of segmentstore or controller are greater than number of nodes. By making the PDB Configurable.
Fixes #497 
Added **maxUnavailableControllerReplicas** and **maxUnavailableSgmentStoreReplicas** fields which will be used to configure the controller and ss pdb respectively. 
Modify the above two field and check inside the controller and ss PDB's they should have the modified values.

Issue-497: Added changes for configuring PDB

---

charts/pravega-operator/templates/pre-delete-hooks.yaml
charts/pravega-operator/values.yaml

Provides a pre-delete hook which ensures that custom resources are deleted before deleting the operator.
Fixes #502 
Allows the operator to be deleted via helm only if the PravegaCluster custom resource has already been deleted, not otherwise.
- If you try to delete the pravega operator before having deleted the PravegaCluster custom resource, the pre-delete job will fail, thereby not allowing the operator from being deleted.
- If you try to delete the pravega operator after the PravegaCluster custom resource has been cleaned up successfully, the operator will also be successfully deleted.

Issue 502: Pravega Operator pre-delete hook

---

pkg/controller/pravegacluster/pravegacluster_controller.go
pkg/controller/pravegacluster/pravegacluster_controller_test.go

Added changes for Avoiding 2 Restarts when Both Version and cm changes are done at the same time. This makes the upgrade process fast and we don't get error messages due to race condition.
Fixes #505 
Code checks for any change in the version of the bk cluster when there are changes in cm and if there is change in the version
then we skip restart of pods and only upgrade the cm
Install pravega cluster then upgrade the cluster along with changing some field in the option we should only see one restart of all pravega(controller and ss) pods and the upgrade should complete.

Issue-505: Added changes for Avoiding 2 Restarts when Both Version and cm changes are done at the same time 

---

charts/pravega/values.yaml
pkg/controller/pravega/pravega_controller.go
pkg/controller/pravega/pravega_segmentstore.go

- introduces the `hostPathVolumeMounts` and `emptyDirVolumeMounts` options as multiple key-value pairs, separated by commas and each consisting of a `<name>`=`<path>` tuple.
- parses the `hostPathVolumeMounts` and `emptyDirVolumeMounts` values.
- adds the extracted values to the `volumes` list and containers' `volumeMounts` list.
Implements #518 
Pravega operator should allow to specify "extra" volumes to be mounted into pravega pods, including pravega segment store pods and pravega controller pods. Such volumes may be used to share data between the hosts and containers.
The code implements the new bookie options: `hostPathVolumeMounts` and `emptyDirVolumeMounts`.
To use "extra" volumes in the bookie pods, in the Bookkeeper options, specify:
- `hostPathVolumeMounts` to add `hostPath` …

Issue 518: Add suport of configurable extra volume mounts

---

charts/pravega/templates/pravega.yaml
charts/pravega/values.yaml

Adding Changes to Allow the latest operator to deploy 0.5.2 operator
Fix #520 
I have made maxunavailable replicas for both ss and controller optional in pravega chart . Which should now allow for deploying of 0.5.2 pravega operator and finally pravega cluster. 
Try deploying 0.5.2 operator with latest charts and then try deploying pravega cluster post that we should be able to deploy both.

Issue-520: Adding Changes to Allow latest operator to deploy 0.5.2 operator

---

test/e2e/pravegacluster_test.go

Remove the invalid test that is not supported
Fixes #532
Comment  out the invalid test.
All end to end tests should pass

Issue 532: Remove the end to end test that is not supported

---

charts/pravega/values.yaml
go.mod
go.sum
pkg/controller/pravega/pravega_segmentstore.go
pkg/controller/pravega/pravega_segmentstore_test.go
pkg/controller/pravegacluster/pravegacluster_controller.go
pkg/test/e2e/e2eutil/pravegacluster_util.go
test/e2e/cmchanges_test.go

Provided support to configure segment store ports. If the port is not mentioned in pravega options,default port will be set as `12345`
Fixes #534
Added support to configure segment store port.
Verified that segment store pods are coming up with different port number, if it is configured.
If port number is not specified, segment store pod is coming up with default port number
Verified changing segment store  port at run time after Pravega is installed. 
Verified changing segment store  port at run time after Pravega is installed with external access.

Issue 534: Provide support to configure segment store port

---

charts/pravega/values.yaml
pkg/controller/pravega/pravega_controller.go
pkg/controller/pravega/pravega_controller_test.go
pkg/controller/pravega/pravega_segmentstore.go
pkg/controller/pravega/pravega_segmentstore_test.go

- introduces the `configMapVolumeMounts` option as multiple key-value pairs, separated by commas and each consisting of a `<configMapName>`:`<configKey>`=`<configFilePath>` tuple.
- parses the `configMapVolumeMounts` values.
- adds the extracted values to the `volumes` list and containers' `volumeMounts` list.
Implements #525 
Pravega operator should allow to specify "extra" configmap volumes to be mounted into pravega pods, including pravega segment store pods and pravega controller pods. Such config volumes may be used to import external configs for pravega use.
The code implements the new pravega option `configMapVolumeMounts`.
To use "extra" volumes in the pravega pods, in the Pravega options, specify:
- `configMapVolumeMounts` to add `configMap` volumes
The option consist of multiple …

Issue 525: Add suport of configurable extra configmap volume mounts

---

charts/pravega/README.md
charts/pravega/values.yaml
charts/pravega/values/large.yaml
charts/pravega/values/medium.yaml
charts/pravega/values/small.yaml
doc/pravega-options.md
pkg/controller/pravega/constants.go
pkg/controller/pravega/pravega_controller.go
pkg/controller/pravega/pravega_controller_test.go
pkg/controller/pravega/pravega_segmentstore.go
pkg/controller/pravega/pravega_segmentstore_test.go
pkg/controller/pravegacluster/pravegacluster_controller_test.go
pkg/test/e2e/e2eutil/pravegacluster_util.go
test/e2e/cmchanges_test.go
test/e2e/pravegacluster_test.go

Removes the hardcoded JVM options from the operator code, so that users can easily set their desired configuration through the charts, and also modify them if required.
Fixes #537, #460 
Removes the hardcoded JVM options from the operator code.
The segmentstore and controller should be configured with the JVM options that are provided within the values.yaml by the user. Also these values can be easily modified even after the pravega cluster has been deployed by editing the pravega cluster spec.

Issue 537: Making JVM Options configurable

---

charts/pravega/values.yaml

Fixing a typo in pravega helm charts
Fixes #549
Fixed the chart issue
Verified installing pravega

Issue 549: Fixing issue in charts

---

charts/pravega-operator/Chart.yaml
charts/pravega-operator/README.md
charts/pravega-operator/values.yaml
charts/pravega/Chart.yaml
charts/pravega/values.yaml
charts/pravega/values/large.yaml
charts/pravega/values/medium.yaml
charts/pravega/values/small.yaml

Updates the pravega operator version within the charts to 0.5.3
Fixes #551 
Changes the default version of the pravega operator within the operator charts to 0.5.3
Should deploy the latest version of pravega operator i.e. 0.5.3

Issue 551: Updating charts to latest version

---

charts/README.md
deploy/version_map.yaml
doc/manual-installation.md
doc/operator-upgrade.md
doc/troubleshooting.md
doc/upgrade-cluster.md
pkg/apis/pravega/v1beta1/pravegacluster_types.go
pkg/apis/pravega/v1beta1/pravegacluster_types_test.go
test/e2e/webhook_test.go

Removes the supported versions configmap from the pravege operator.
Fixes #564 
Removes the version validation from the validating webhook at the time of installation or upgrades of the pravega cluster. However the webhook will continue to check the format of the image being provided and will not allow any downgrade, unless while trying to rollback the cluster in case of a failed upgrade.
The pravega operator should allow installation of any pravega version given in the correct format (i.e. *MAJOR*.*MINOR*.*PATCH*-*XXXX*), and should also allow upgrades to any other pravega version. Downgrades are however not allowed.
The following scenarios have been tested
- Upgrading the pravega operator from version 0.5.4 (which contains the version …

Issue 564: Removing supported versions configmap

---

Makefile

Hardcodes the base version of the operator in the Makefile, which needs to be updated after every pravega operator release, to serve as the base version.
Fixes #566 
Hardcodes the pravega operator base version in the Makefile to compute the version for pravega operator images that are build using `make build-image` command.
The final version for the pravega operator is computed in the following format inside the Makefile
```
{base_version}-{number_of_commits}-{commit_id}
```
Running the command `make build-image` should build the pravega operator image with version in the desired format

Issue 566: Including operator base version in Makefile

---

test/e2e/resources/kubernetes_master_install.sh
test/e2e/resources/kubernetes_slave_install.sh

Kubectl version is taken as v1.22 in github action causing end to end tests to fail
Fixes #571
Update kubernetes version to 1.21
End to end tests should pass

Issue 571: Fixing end to end tests

---

doc/tls.md
pkg/apis/pravega/v1beta1/pravega.go
pkg/apis/pravega/v1beta1/pravegacluster_types.go
pkg/controller/pravega/pravega_controller.go
pkg/controller/pravega/pravega_segmentstore.go
pkg/controller/pravegacluster/pravegacluster_controller.go
pkg/controller/pravegacluster/pravegacluster_controller_test.go
pkg/controller/pravegacluster/upgrade.go
pkg/util/pravegacluster.go
pkg/util/pravegacluster_test.go
test/e2e/pravegacluster_test.go

Integrates the apis exposed by the new healthcheck framework which is compatible with pravega version >= 0.10.0, while not breaking backward compatibility.
Fixes #357 
Uses the latest healthcheck apis for monitoring the health of the controller and segmentstore pods when any pravega version starting 0.10.0 is deployed. Also, uses the earlier liveness and readiness probes for the controller and segmentstore pods when pravega version lower than 0.10.0 has been deployed. 
When pravega version is lesser than 0.10.0, the following healthchecks are invoked
**for SegmentStore**
```
livenessProbe:
exec:
command:
- /bin/sh
- -c
-  netstat -ltn 2> /dev/null | grep 12345 || ss -ltn 2> /dev/null | grep 12345
readinessProbe:
exec:
command:
- /bin/sh
- …
```

Issue 357: Integrating health checks

---

doc/pravega-options.md
doc/upgrade-cluster.md

Signed-off-by: Nishant Gupta <Nishant_Gupta3@dell.com>
Set the correct name for controller JVM options setting in the documentation so as to align it with that of json string set in the [code](https://github.com/pravega/pravega-operator/blob/v0.5.5/pkg/apis/pravega/v1alpha1/pravega.go#L100)
Fixes #577
Currently the name of controller JVM options setting in documentation file is listed incorrectly as `controllerJvmOptions`, while in the [code](https://github.com/pravega/pravega-operator/blob/v0.5.5/pkg/apis/pravega/v1alpha1/pravega.go#L100) the json string is set to `controllerjvmOptions`. This documentation update is to make the JVM options setting equal to the one set in the code 
Make sure the value in document matches to the json string in the …

Issue 577: Set the correct name for controller JVM options setting in the documentation

---

doc/auth-handlers.md
doc/configuration.md
doc/external-access.md
doc/init-containers.md
doc/longtermstorage.md
doc/manual-installation.md
doc/pravega-options.md
doc/rbac.md
doc/release_process.md
doc/service-sts-name-configuration.md
doc/sidebars.js
doc/troubleshooting.md
doc/upgrade-cluster.md
doc/webhook.md

Convert to Docusaurus format.
Fixes #593
Allows operator docs to be rendered along with other docs as previewed here: https://pravega.io/docs/snapshot

Issue 593: Convert markdown to support Docusaurus and combined docs repo

---

pkg/apis/pravega/v1beta1/pravega.go
pkg/apis/pravega/v1beta1/pravegacluster_types.go
pkg/apis/pravega/v1beta1/pravegacluster_types_test.go
test/e2e/webhook_test.go

Signed-off-by: Nishant Gupta <Nishant_Gupta3@dell.com>
When deploying the pravega cluster,  the options `bookkeeper.ensemble.size`  `bookkeeper.write.quorum.size`  `bookkeeper.ack.quorum.size` should be set such that the following condition is satisfied: `bookkeeper.ensemble.size >= bookkeeper.write.quorum.size >= bookkeeper.ack.quorum.size`
Fixes #587
The code preforms the following checks :
- `bookkeeper.ensemble.size >=  bookkeeper.write.quorum.size  >= bookkeeper.ack.quorum.size`
- If `bookkeeper.ensemble.size == 1` then `bookkeeper.write.quorum.racks.minimumCount.enable` should be set to `false`
Install a pravega cluster with different values of  `bookkeeper.ensemble.size`  `bookkeeper.write.quorum.size`  `bookkeeper.ack.quorum.size` and in case the above mentioned condition in not …

Adding validation checks for Bookkeeper Deployments

---

pkg/apis/pravega/v1beta1/pravega.go

when test mode is enabled, rollback timeout is not set to any default value. Due to that upgrade is not getting any time to complete and is failing
Fixes #601
Set the Rollback timeout to `10 min` even if test mode is enabled
Verified that  upgrade is working fine with test mode is enabled.

Issue 601: Upgrading Pravega minor version is failing with test mode enabled

---

pkg/apis/pravega/v1beta1/pravegacluster_types.go

Signed-off-by: Andrey Andreev <andrey_andreev@dell.com>
The import of k8sutil is removed in pravegacluster_types.go and k8s.GetOperatorName() is replaced by the function OperatorName().
The package k8sutil [was removed](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.0.0/#removed-package-pkgk8sutil) from operator-sdk in version 1.0.0. This blocks using of PravegaCluster as a secondary resource in projects which use operator-sdk 1.0.0+.
Implements OperatorName() function that returns the value of OPERATOR_NAME env variable and/or error in case of empyt or not set variable.
- pravegacluster_types.go and a corresponding package don't have dependency to k8sutil
- ZKMETA_CLEANUP_ERROR and UPGRADE_ERROR events should have the same operator name as before in ReportingController …

Issue 605: Remove dependency to k8sutil in pravegacluster_types.go

---

cmd/manager/main.go
deploy/webhook.yaml

Update the default web hook port to `9443`
Fixes #609
Updated the port
All e2e should pass

Issue 609: Updating default web hook port

---

pkg/apis/pravega/v1beta1/pravegacluster_types.go
pkg/apis/pravega/v1beta1/pravegacluster_types_test.go
test/e2e/webhook_test.go

Adding validation for authentication settings
Fixes #611
If authentication is enabled,  webhook validation will  ensure
a. Pravega.Options["autoScale.controller.connect.security.auth.enable"]/p.Spec.Pravega.Options["autoScale.authEnabled"] is set to true
b. controller.security.auth.delegationToken.signingKey.basis is present
c. autoScale.security.auth.token.signingKey.basis is present
d. b and c are equal
If authentication is disabled. validation will ensure  Pravega.Options["autoScale.controller.connect.security.auth.enable"]/p.Spec.Pravega.Options["autoScale.authEnabled"] is set to false
Verified by setting these options and installed pravega and saw that proper error message is displayed.

Issue 611: Adding validation for authentication settings

---

.github/workflows/CI.yml
controllers/upgrade.go
controllers/upgrade_test.go
test/e2e/resources/zookeeper_crd.yaml

Made sure that correct labels are used for selecting pods during upgrade
Fixes #620
During upgrade process, if the labels are also changed, while listing pods it is looking for pods with updated labels and which results in pods are not getting listed. Corrected the logic for finding labels
In order  to fix this we are using a subset of labels that will be present always.  labels used in selector are
``` 
"app": "pravega-cluster",
"pravega_cluster": pravegaCluster.Name,
```
Verified that upgrade is working fine even with the change of labels.

Issue 620: Fix for pravega image upgrade failure

---

controllers/upgrade.go

While doing upgrade of pravega cluster, we are finding outdated pod in segment store using the pravega cluster labels. Since the controller and segment store share the same labels, outdated pod lists controller pod as well and upgrade is not happening correctly.
Fixes #620
Corrected the labels for finding outdated pod
Verified that upgrade is working fine

Issue 620: Fix for pravega upgrade failure

---

main.go

imports in `main.go` file was wrongly referring bookkeeper imports
Fixes #628
Corrected the imports
Verified pravega operator installation by enabling disablefinalizer flag and finalizer is not getting added

Issue 628: Fix for disable finalizer flag is not functioning correctly

---

controllers/pravega_controller.go

Updating the controller PDB policy
Fixes #630
Currently in controller PDB, the `maxunavailableReplicas` set in values file is used for `minAvailable` . Corrected the policy. Also if the replica count is 1 setting maxunavailable replicas to `0` as in segment store
Verified that able to configure PDB with these settings

Issue 630: Updating controller pdb policy

---

controllers/pravegacluster_controller.go

While doing restart of sts, labels are not passed correctly to list pods. Corrected the labels
Fixes #634
Corrected the labels, so that the  pods are listed and restarted correctly
Verified that after changing segment store pod labels,  pods are restarted

Issue 634: Segment store pods are not restarted for labels updation

---

Dockerfile

Signed-off-by: Nishant Gupta <Nishant_Gupta3@dell.com>
Update alpine version to fix [CVE-2022-30065](https://security.alpinelinux.org/vuln/CVE-2022-30065) , [CVE-2022-28391](https://security.alpinelinux.org/vuln/CVE-2022-28391) and [CVE-2022-1292](https://security.alpinelinux.org/vuln/CVE-2022-1292).
Fixes #636
Update alpine version to 3.16
_(Steps to verify that the changes are effective)_
- Pull the latest docker image
- Spawn a container out of that image and go inside the container
- run the command apk list | grep busybox to check the installed version of busybox
- run the command apk list | grep openssl to check the installed version of openssl

Update alpine version to fix CVEs

---

controllers/upgrade.go

Pravega cluster upgrade is failing in certain cases. In failed scenarios, while deleting the pod, we are getting error pod not found. Due to that error upgrade status is set to failure and due to that subsequent upgrade of pods is not happening
Fixes #643
Made changes to not return error in the case of pod deletion fails with pod not found error. This ensures that remaining pods can be upgraded successfully. 
Verified upgrade of pravega cluster multiple times and is successful

Issue 643: Pravega cluster upgrade is failing intermittently

---

api/v1beta1/pravega.go
config/crd/bases/pravega.pravega.io_pravegaclusters.yaml
controllers/pravega_controller.go

Added support to provide customized env variables to controller pods
Fixes #646
Added new field `ControllerEnvVars` in Pravega spec. Also updated CRD
Verified that able to provide customized env variables to controller pods

Issue 646: Add support for providing customized environment variables to controller

---

controllers/pravegacluster_controller.go

Added support to update the annotations and labels at run time for controller service
Fixes #657
In controller reconcile service, if there is change in service like annotations, labels it will be updated
Verified by adding new annotations at run time

Issue 657: Providing support to update controller service annotations

---

controllers/pravega_segmentstore.go

Updating the segment store service port incrementally if  `SegmentStoreLoadBalancerIP` is set
Fixes #670
If we are using same segment store service IP with different ports, in case of admin port as well port number needs to be incremented. If it is not incremented will give port conflict
Verify segment store pods are coming up fine

Issue 670: Updating the segmentstore port

---

controllers/upgrade.go

Fixing intermittent upgrade failure of pravega.
Added some more conditions to handle error scenarios
Fixes #643
while during segmentstore update, it fails to get the pod sometimes. Issue is happening because while it tries to get an outdated pod, it has already updated. So added more checks to post error only if all pods were not updated
Peformed upgrade multiple time and issue is not seen

Issue 643: Fixing intermittent upgrade failure

---

api/v1beta1/pravegacluster_types.go
config/crd/bases/pravega.pravega.io_pravegaclusters.yaml
controllers/pravega_segmentstore.go
pkg/util/pravegacluster.go

While deploying pravega with 12 segmentstore pods, segmentstore service was using one of the ports used by other service `containerd` and was causing conflict
Added new spec field in CRD as `reservedPortList` and while assigning port to service ensure that it is not in reserved port List 
Fixes #674
Assigning port to segment store services which is not in the reserved portList, if it finds conflict next  port will be assigned.
Verified pravega installation with 12 segmentstore pods and ensured that ports mentioned in reservedportlist are getting skipped.

Issue 674: Fix for segment store services are not coming up properly
