pravega/pravega-operator

- example/cr-detailed.yaml
- example/cr.yaml
> [issue-32] Update Pravega version to 0.3.2

- Dockerfile
- Makefile
Adds Multi-Stage Dockerfile which builds compiles the GO operator in one step before generating the resulting image in another.
Signed-off-by: David Maddison <maddisondavid@gmail.com>
> Added Multi-Stage Docker build

- README.md
Update the ZooKeeper operator reference now the we have released our own ZooKeeper operator.
Fix #71
Signed-off-by: Adrian Moreno <adrian@morenomartinez.com>
> Issue 71: Update ZooKeeper operator reference

- CONTRIBUTING.md
Signed-off-by: Aparna <Aparna.Rr@emc.com>
File name CONTRIBUTING.md  is created. This file contains the reference to the wiki page: 
https://github.com/pravega/pravega-operator/wiki/Contributing
Closes #58
> Issue 49: Included CONTRIBUTING.md

- README.md
Signed-off-by: Aparna <Aparna.Rr@emc.com>
*Change log description
1. TOC added
2. Included the following sections:
a. Run operator locally added
b. Releases added.
*Purpose of the change
Fixes #38, Closes #43
> Issue 38: TOC added to README.md

- .gitignore
- charts/pravega-operator/Chart.yaml
- charts/pravega-operator/templates/_helpers.tpl
- charts/pravega-operator/templates/cluster-rbac.yaml
- charts/pravega-operator/templates/crd.yaml
- charts/pravega-operator/templates/operator.yaml
- charts/pravega-operator/templates/rbac.yaml
- charts/pravega-operator/values.yaml
Added Helm chart to deploy pravega-operator into Kubernetes cluster
Fix #20
Signed-off-by: David Maddison <maddisondavid@gmail.com>
> Issue 20: Added Helm Chart

- README.md
Signed-off-by: Aparna <Aparna.Rr@emc.com>
1. Content base on issue#87 included:
> Issue 95: Updated README.md

- .travis.yml
- Makefile
- test/e2e/resources/zookeeper.yaml
- Run operator tests on GKE instead of Minikube
Test have been quite unstable lately due to resource constrains in Minikube
GKE-based tests should pass.
---
> Run tests on GKE

- example/cr-detailed.yaml
Refractor cr-detailed.yaml file
Fix #147
Signed-off-by: wenqi <Wenqi.Mou@emc.com>
> Fix cr-detailed

- README.md
- doc/external-access.md
- Create external access guide with instructions to configure it, enable it and sample manifests.
- Fix #161 
---
> Issue 161: Create external access guide

- cmd/manager/main.go
Import oidc package in the `main.go` file.
Fix #172 
The operator could run locally.
Signed-off-by: wenqi <Wenqi.Mou@emc.com>
> Issue-172: Import oidc package

- README.md
- doc/bookkeeper-options.md
- doc/configuration.md
- doc/development.md
- doc/manual-installation.md
- doc/pravega-options.md
- doc/rbac.md
- doc/tier2.md
- doc/troubleshooting.md
- doc/upgrade-cluster.md
Reorganize README
Fix #169 
Signed-off-by: wenqi <Wenqi.Mou@emc.com>
> Issue 169: Reorganize README

- .travis.yml
- Makefile
- README.md
Add code coverage for Pravega operator repo.
Refer to this [repo](https://github.com/codecov/example-go)
Fix #174 
Code cov report should be displayed in this PR
Signed-off-by: wenqi Wenqi.Mou@emc.com
> Issue 174: Add code coverage report

- README.md
> Minor update in readme.md

- doc/upgrade-cluster.md
Fix upgrade order in documentation
Fix #183
---
> Issue 183: Fix upgrade order in documentation

- doc/troubleshooting.md
Add doc for node recovery
Fix #171
> Issue 171: Add doc for node recovery

- README.md
- doc/configuration.md
- doc/webhook.md
Add doc for webhook and fix Kubernetes requirement version.
Fix #209 
> Add doc for admission webhook

- pkg/controller/pravega/bookie.go
Make the volume mount right.
Fix #221 
Volume should be mounted to the right dir.
> Issue 221: Fix mixed up volumes mount

- doc/external-access.md
Add documentation for segment store external dns to operator external access documentation.
Fixes #256
> Issue:256 Add documentation for external dns

- pkg/controller/pravegacluster/upgrade.go
When an upgrade is triggered, new pods with the updated version start to replace the old ones. But, the ConfigMap objects are not updated and are reused from one version to another. This poses a problem since different versions of Pravega and BookKeeper may require a different configuration to be set. 
Hence, the ConfigMap for the Controller, Segmentstore, and BookKeeper needs to be updated or recreated and used by the new pods.
Fixes #154 
The code updates the ConfigMap of the Controller, Segmentstore and Bookkeeper while it is upgrading each of these components, so that the new pods make use of the updated ConfigMap.
To reproduce the issue, added an additional configuration parameter that would be set to the ConfigMap if `version >= …
> Issue 154: Update ConfigMap during upgrade

- README.md
- doc/upgrade-operator.md
Add doc for operator upgrade
Fix #270
> Issue 270: Add doc for operator upgrade

- doc/bookkeeper-options.md
- doc/pravega-options.md
Add doc for passing JVM options
Fix #279
> Issue 279: Add doc for how to pass JVM options

- charts/pravega/values.yaml
- deploy/crds/pravega_v1alpha1_pravegacluster_cr.yaml
- doc/development.md
- doc/upgrade-cluster.md
Updated the Upgrade Documentation to remove the following warning 
```
Warning: The upgrade feature is still considered experimental, so its use is discouraged if you care about your data.
```
as the upgrade process we follow now is non-disruptive and does not cause any data loss.
Fixes #320
> Issue 320: Updating Upgrade documentation

- README.md
- doc/manual-installation.md
- example/cr-detailed.yaml
Updating the pravega manifest inside `example` directory to reflect changes of splitting Pravega and Bookkeeper. 
Fixed #346
> Issue 346: Updating example pravega manifest

- doc/minikube_setup.md
Added a document which provides the steps that need to be followed to setup a minikube VM and create a working Pravega Cluster within it with optimal resources.
Fixes #344 
Following the steps mentioned in the document, you should be able to deploy Pravega (0.7+) on minikube and successfully execute benchmark tests on it.
> Issue 344: Pravega Setup on Minikube

- doc/tier2.md
Signed-off-by: kevinhan88 <kevinhan88@gmail.com>
added instruction flow for updating ECS credentials
Closes #365 
Added instructions into tier2.md
After following the steps provided, ECS credentials will be updated for Segmentstores.
> Issue-365: added instruction flow for updating ECS credentials

- charts/pravega-operator/Chart.yaml
- charts/pravega-operator/templates/clusterrole.yaml
- charts/pravega-operator/templates/operator.yaml
- charts/pravega-operator/values.yaml
- deploy/crds/pravega_v1alpha1_pravegacluster_cr.yaml
- deploy/operator.yaml
- deploy/role.yaml
Updates the operator charts with the required clusterroles.
Assigning the right clusterroles to the operator.
Using the updated charts you should be able to successfully install pravega operator 0.4.x and a pravega cluster.
> Updating Operator Charts

- setup/README.md
- setup/pravegacluster.sh
Changed the Install Script to work with both helm versions 2 and 3
Install script was working only with helm2, so changes were needed to make it work with helm version 3 as well.
Provides support so that the install script works with an environment having helm version 3 also
Run the install script with helm version 3 as well as with helm version 2
> helm3 supported script added

- pkg/apis/pravega/v1alpha1/pravegacluster_types_test.go
- pkg/apis/pravega/v1alpha1/status_test.go
- pkg/apis/pravega/v1alpha1/zz_generated.deepcopy_test.go
- pkg/apis/pravega/v1beta1/pravegacluster_types_test.go
- pkg/apis/pravega/v1beta1/status_test.go
- pkg/apis/pravega/v1beta1/zz_generated_deepcopy_test.go
- pkg/controller/pravega/pravega_controller_test.go
- pkg/controller/pravega/pravega_segmentstore_test.go
- pkg/controller/pravegacluster/upgrade_test.go
- pkg/util/pravegacluster_test.go
Increased the coverage of the packages v1alpha1, v1beta1 and util
Fixes #231
Added unit tests.
Unit tests are passing
> Issue 231:  Increase pravega-operator code coverage

- pkg/controller/pravega/pravega_controller.go
- pkg/controller/pravega/pravega_controller_test.go
In the case of controller, while creating configmap debuglogging level was not populated.
Fixes #412
If the DebugLogging is set in Pravega spec, populate the log.level in controller configmap
Enable debug Logging and verify debug logs are coming in controller.
> Added fix for populating loglevel in controller

- README.md
- charts/pravega-operator/README.md
- charts/pravega/README.md
- doc/manual-installation.md
- doc/operator-upgrade.md
- go.sum
- setup/README.md
- setup/pravegacluster.sh
Simplifies the pravega cluster installation script to a few lines of code. Also updates documentation to reflect the correct versions of the pravega dependencies.
Fixes #419 
`./pravegacluster.sh deploy` should deploy a pravega cluster with all its dependencies
`./pravegacluster.sh destroy` should remove the deployed pravega cluster with all its dependencies
> Issue 419: Simplifying the pravega installation script

- charts/pravega/templates/pravega.yaml
- setup/pravegacluster.sh
Makes changes to the charts to be able to add annotations to segmentstore and controller services. Also makes changes to the pravega installation script so it does not fail if uninstallation of a single component fails.
> Chart modifications

- README.md
- charts/pravega-operator/README.md
- charts/pravega/README.md
- doc/operator-upgrade.md
Updates documentation with the correct helm version required.
> Updating Documentation

- .github/workflows/CI.yml
- test/e2e/resources/kubernetes_master_install.sh
- test/e2e/resources/kubernetes_slave_install.sh
End to end tests are failing in creating clusters as well as incompatibility with docker versions 
Fixes #558
Changed the location of cluster . Also modified to install  a specific docker version
Verified that tests are passing
> Issue 558: Fixing end to end tests 

- Dockerfile
Updating alpine image to `3.14`
Fixes #572
Updating alpine image to fix security vulnerabilities
All e2e should pass
> Issue 572: Upgrade alpine image to fix security vulnerabilities 

- Makefile
Updating base version of operator to  `0.5.6`
Fixes #575
Change Base version
Subsequent builds should show the updated version
> Issue 575: Updating base version of operator

- Makefile
Updating base version in Makefile to `0.5.7`
Fixes #599
Update the base version in Makefile
Ensure that subsequent builds are coming up with new version
> Issue 599: Updating base version in Makefile

- main.go
Added flag disable finalizer
Fixes #618
Added disable finalizer flag.
passing namespace when manager is starting.
Calling customized leader.Become function 
All e2e should pass
> Issue 618: Adding support to disable finalizer

- .github/workflows/CI.yml
- api/v1beta1/pravega.go
- config/crd/bases/pravega.pravega.io_pravegaclusters.yaml
- config/crd/kustomization.yaml
- controllers/pravega_segmentstore.go
Added support to customize segment  store conatainers, env and volumes.
Fixes #638
Added new fields in Pravega spec for containers, env, and volumes for segment store pods
Verified that able to customize these fields
> Issue 638: Adding support for customized containers and env to segmentstore pods
